# Generated by Django 6.1 on 2026-09-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_category_post_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="core.category"
            ),
        ),
    ]
