# Generated by Django 5.2.16 on 2026-07-26 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["title"],
                "permissions": [("publish_book", "Can publish book")],
            },
        ),
    ]
